In [1]:
import aoc
import cmath
import collections
from collections import defaultdict
from functools import cache, reduce
import itertools as it
import math
import more_itertools as mit
import networkx as nx
import numpy as np
import operator as op
import pandas as pd
import re
import statistics
import utils

In [2]:
test_input="""5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

# Part 1

In [26]:
# run to solve part 1
def valid(x, y):
    return x >= 0 and y >= 0 and x < 10 and y < 10

def adj(pos):
    posx, posy = pos
    return ((posx + x, posy + y) for x in range(-1, 2) for y in range(-1, 2) if (x, y) != (0, 0) and valid(posx + x, posy + y))

def step(grid):
    grid += 1
    all_flashes = grid > 9
    flashes = all_flashes
    while np.any(flashes):
        for pos in it.product(range(10), range(10)):
            if flashes[pos]:
                for a in adj(pos):
                    #print(a)
                    grid[a] += 1
        flashes = (~all_flashes) & (grid > 9)
        all_flashes = grid > 9
    grid[grid > 9] = 0
    return all_flashes

def part_1(aoc_input):
    lines = aoc_input.splitlines()
    all_digits = re.findall(r"(\d)", aoc_input)
    arr = np.array(all_digits, int)
    arr = arr.reshape(10, 10)
    print(arr)
    count = 0
    for i in range(100):
        flashes = step(arr)
        s = np.sum(flashes)
        #print(arr)
        #print(s)
        count += s
    return count

part_1_test_answer = part_1(test_input)
print("TEST RESULT: ", part_1_test_answer)
part_1_answer = part_1(aoc.get_input(2021, 11))
print("ACTUAL RESULT: ", part_1_answer)

[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
TEST RESULT:  1656
[[2 5 6 6 8 8 5 4 3 2]
 [3 8 5 7 4 1 4 3 5 7]
 [6 7 6 1 5 4 3 2 4 7]
 [5 4 7 7 3 3 2 1 1 4]
 [3 7 3 1 5 8 5 3 8 5]
 [1 7 1 6 7 8 3 1 7 3]
 [1 2 7 7 3 2 1 6 1 2]
 [3 3 7 1 1 7 6 1 4 8]
 [1 1 6 2 5 7 8 2 8 5]
 [6 1 4 4 7 2 6 3 6 7]]
ACTUAL RESULT:  1647


In [27]:
# run to submit part 1

aoc.submit_answer(2021, 11, 1, part_1_answer)

Submitting for YEAR 2021, DAY 11, LEVEL 1: 1647... Correct!


# Part 2

In [29]:
# run to solve part 2

def valid(x, y):
    return x >= 0 and y >= 0 and x < 10 and y < 10

def adj(pos):
    posx, posy = pos
    return ((posx + x, posy + y) for x in range(-1, 2) for y in range(-1, 2) if (x, y) != (0, 0) and valid(posx + x, posy + y))

def step(grid):
    grid += 1
    all_flashes = grid > 9
    flashes = all_flashes
    while np.any(flashes):
        for pos in it.product(range(10), range(10)):
            if flashes[pos]:
                for a in adj(pos):
                    #print(a)
                    grid[a] += 1
        flashes = (~all_flashes) & (grid > 9)
        all_flashes = grid > 9
    grid[grid > 9] = 0
    return all_flashes

def part_2(aoc_input):
    lines = aoc_input.splitlines()
    all_digits = re.findall(r"(\d)", aoc_input)
    arr = np.array(all_digits, int)
    arr = arr.reshape(10, 10)
    print(arr)
    count = 0
    for i in range(10000000):
        flashes = step(arr)
        if np.sum(flashes) == 100:
            return i + 1

part_2_test_answer = part_2(test_input)
print("TEST RESULT: ", part_2_test_answer)
part_2_answer = part_2(aoc.get_input(2021, 11))
print("ACTUAL RESULT: ", part_2_answer)

[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
TEST RESULT:  195
[[2 5 6 6 8 8 5 4 3 2]
 [3 8 5 7 4 1 4 3 5 7]
 [6 7 6 1 5 4 3 2 4 7]
 [5 4 7 7 3 3 2 1 1 4]
 [3 7 3 1 5 8 5 3 8 5]
 [1 7 1 6 7 8 3 1 7 3]
 [1 2 7 7 3 2 1 6 1 2]
 [3 3 7 1 1 7 6 1 4 8]
 [1 1 6 2 5 7 8 2 8 5]
 [6 1 4 4 7 2 6 3 6 7]]
ACTUAL RESULT:  348


In [30]:
# run to submit part 2

aoc.submit_answer(2021, 11, 2, part_2_answer)

Submitting for YEAR 2021, DAY 11, LEVEL 2: 348... Correct!
